# Generated by Django 4.0.6 on 2022-09-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='prod', max_length=200),
        ),
    ]
