# Generated by Django 4.0.6 on 2022-09-26 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
