# Generated by Django 4.0.6 on 2022-09-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_cart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
