# Generated by Django 4.0.6 on 2022-09-29 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
    ]
