# Generated by Django 4.0.6 on 2022-10-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_product_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Samsung', 'Samsung'), ('Tecno', 'Tecno'), ('Nokia', 'Nokia'), ('Iphone', 'Iphone')], max_length=50, null=True),
        ),
    ]
