# Generated by Django 4.0.6 on 2022-10-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_cart_price_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
